.TH gridsite-delegation 8 "March 2006" "gridsite-delegation" "GridSite Manual"
.SH NAME
.B gridsite-delegation.cgi
\- CGI implementation of GridSite/gLite GSI delegation Web Service
.SH SYNOPSIS
.B gridsite-delegation.cgi

.SH DESCRIPTION
.B gridsite-delegation.cgi
is a server-side implementation of the GridSite/gLite GSI delegation Web
Service

.SH AUTHOR
Andrew McNab <Andrew.McNab@manchester.ac.uk>

gridsite-delegation.cgi is part of GridSite: http://www.gridsite.org/

.SH "SEE ALSO"
.BR htproxyput(1)
