.TH urlencode 1 "November 2003" urlencode "URLENCODE Manual"
.SH NAME
.B urlencode
\- convert strings to or from URL-encoded form
.SH SYNOPSIS
.B urlencode 
[-m|-d] 
.I string [string ...]
.SH DESCRIPTION
.B urlencode
encodes strings according to RFC 1738. 

That is, characters A-Z a-z 0-9 . _ 
and - are passed through unmodified, but all other characters are
represented as %HH, where HH is their two-digit upper-case hexadecimal ASCII
representation.
For example, the URL http://www.gridpp.ac.uk/gridsite/ becomes
http%3A%2F%2Fwww.gridpp.ac.uk%2Fgridsite%2F

.B urlencode
converts each character in all the strings given on the command line. If
multiple strings are given, they are concatenated with separating spaces
before conversion.

.SH OPTIONS
.IP "-m"
Instead of full conversion, do GridSite "mild URL encoding" in which A-Z a-z
0-9 . = - _ @ and / are passed through unmodified. This results in slightly
more human-readable strings but the application must be prepared to create
or simulate the directories implied by any slashes.

.IP "-d"
Do URL-decoding rather than encoding, according to RFC 1738. %HH and %hh
strings are converted and other characters are passed through unmodified,
with the exception that + is converted to space.

.SH EXIT CODES
0 is always returned.

.SH BUGS
Not enough beta testing (hint hint...)

.SH AUTHOR
Andrew McNab <mcnab@hep.man.ac.uk>

urlencode is part of GridSite: http://www.gridpp.ac.uk/gridsite/
